[project]
name = "university-math-with-python"
version = "0.1.0"
description = "Exploring University Mathematics with Python by Siri Chongchitnan. Experiments, understanding, trial and errors."
authors = [
    {name = "Dinesh Kasti",email = "katidin@gmail.com"}
]
license = {text = "GNU"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy (>=2.2.4,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
